from os import getenv

INFURA_URL_TESTNET = getenv("INFURA_URL_TESTNET")
INFURA_URL_MAINNET = getenv("INFURA_URL_MAINNET")

GASSTATION_API_TOKEN = getenv("GASSTATION_API_TOKEN")
ETHERSCAN_API_TOKEN = getenv("ETHERSCAN_API_TOKEN")
ETH_MAX_GAS = 200000
ETH_MAX_GAS_DEPOSIT_LOOT = 60000
ETH_MAX_GAS_PRICE_GWEI = 120
MAX_GAS_PRICE_GWEI = 120
GAS_TRACKER_URL = "https://api.etherscan.io/api/"
GAS_MULTIPLIER = 3

LOCALUSDT_FEE = 8

############################
# Ethereum
############################

HOT_WALLET_ADDRESS_MAINNET = getenv("HOT_WALLET_ADDRESS_MAINNET")
HOT_WALLET_ADDRESS_TESTNET = getenv("HOT_WALLET_ADDRESS_TESTNET")
HOT_WALLET_PRIVATE_KEY_MAINNET = getenv("HOT_WALLET_PRIVATE_KEY_MAINNET")
HOT_WALLET_PRIVATE_KEY_TESTNET = getenv("HOT_WALLET_PRIVATE_KEY_TESTNET")

ABI_FILEPATH_MAINNET = "contract_USDT_abi.json"
ABI_FILEPATH_TESTNET = "contract_USDT_abi_test.json"

USDT_CONTRACT_ADDRESS_MAINNET = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
USDT_CONTRACT_ADDRESS_TESTNET = "0x4EbedbcB794F9B0ff1D16d41FcbC22B27b2111fB"

LAST_BLOCKS_TO_PARSE = 10

