# docker-compose config for develop server
version: '3'
services:
  frontend:
    container_name: localusdt-frontend
    restart: always
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:master-latest
    volumes:
      - ./static/:/app/static/
    depends_on:
      - backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: localusdt-backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop 'uvloop' --lifespan on --proxy-headers --workers 2
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.backend

  celeryworker:
    container_name: localusdt-celeryworker
    command: sh -c "sleep 50 && celery worker -A celery_app -P celery_pool_asyncio:TaskPool --loglevel=INFO"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
      - .env.backend

  celerybeat:
    container_name: localusdtt-celerybeat
    command: sh -c "sleep 60 && celery beat -A celery_app --scheduler celery_pool_asyncio:PersistentScheduler --loglevel=INFO"
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:master-latest
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - rabbitmq
      - celeryworker
    env_file:
      - .env
      - .env.backend

  rabbitmq:
    container_name: localusdt-rabbitmq
    image: rabbitmq:3.8.4-alpine
    ports:
      - 5672:5672
    env_file:
      - .env.rabbitmq

  db:
    container_name: localusdt-mongodb
    image: mongo:4.2-bionic
    command: mongod --port 27017 --auth
    restart: always
    volumes:
      - localusdt-mongodb-develop:/data/db
    ports:
      - 27017:27017
    env_file:
      - .env
      - .env.db

volumes:
  localusdt-mongodb:
