# docker-compose config for develop server
version: '3'
services:
  frontend:
    container_name: localusdt-frontend
    restart: always
    command: yarn start
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/frontend:develop-latest
    depends_on:
      - backend
    expose:
      - "3014"
    ports:
      - "3014:3014"
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: localusdt-backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop 'uvloop' --lifespan on --proxy-headers
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/backend:develop-latest
    depends_on:
      - db
    expose:
      - 8014
    ports:
      - 8014:8014
    env_file:
      - .env
      - .env.backend

  db:
    container_name: localusdt-mongodb
    restart: always
    image: mongo:4.2-bionic
    command: mongod --port 27022 --auth
    ports:
      - 27022:27022
    env_file:
      - .env
      - .env.db
