# docker-compose config for local development
version: '3'
services:
  frontend:
    container_name: localusdt-frontend-local
    command: yarn dev
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.frontend.local
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.frontend

  backend:
    container_name: localusdt-backend-local
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop 'uvloop' --lifespan on --reload --proxy-headers
    build:
      context: ./
      dockerfile: deployment/dockerfiles/Dockerfile.backend.local
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.backend

  db:
    container_name: localusdt-mongodb-local
    image: mongo:4.2-bionic
    command: mongod --port 27017
    ports:
      - 27017:27017
    env_file:
      - .env.db
