FROM node:13.8-buster

ENV DEBUG=false
ENV ENV=production
ENV NODE_ENV=production
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
ENV API_URL=https://localusdt.com/api/
ENV API_URL_BROWSER=https://localusdt.com/api/
ENV SENTRY_DSN=https://905f54d0abc44d54ace2ead8e0a33f28@sentry.elastoo.com/17
ENV API_WS_URL=wss://localusdt.com/api/

COPY ./frontend/ /app/
WORKDIR /app/

# Install Yarn if it is not installed
RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install && yarn build
