FROM node:13.8-buster

ENV DEBUG=true
ENV ENV=develop
ENV NODE_ENV=develop
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3014
ENV API_URL=https://localusdt-dev.elastoo.com/api
ENV API_URL_BROWSER=https://localusdt-dev.elastoo.com/api
ENV SENTRY_DSN=https://0af76331465c474db03105bfa9b3dd92@sentry.elastoo.com/11

COPY ./frontend/ /app/
WORKDIR /app/

# Install Yarn if it is not installed
RUN yarn -v || npm install -g yarn

# Install requirements
RUN yarn install && yarn build
